/**
 * Technical terms related to biomechanics, physiology, anthropometry, and sports science
 * that should be highlighted in the query interface.
 */
const technicalTerms = [
  // Anthropometric terms
  "anthropometric",
  "anthropometry",
  "height",
  "weight",
  "BMI",
  "body mass index",
  "lean mass",
  "body fat",
  "circumference",
  "segment",
  "segmental",
  "length",
  "width",
  "depth",
  "volume",
  "density",
  "surface area",
  "stature",
  "proportions",
  
  // Body segments
  "head",
  "neck",
  "thorax",
  "abdomen",
  "pelvis",
  "arm",
  "forearm",
  "hand",
  "thigh",
  "shank",
  "foot",
  "trunk",
  "limb",
  "upper limb",
  "lower limb",
  
  // Biomechanical terms
  "biomechanics",
  "biomechanical",
  "center of mass",
  "center of gravity",
  "moment of inertia",
  "torque",
  "force",
  "power",
  "velocity",
  "acceleration",
  "momentum",
  "kinetics",
  "kinematics",
  "stiffness",
  "elasticity",
  "compliance",
  "joint",
  "rotation",
  "translation",
  "gait",
  "stride",
  "stride length",
  "stride frequency",
  "ground reaction force",
  "contact time",
  "flight time",
  
  // Physiological terms
  "physiology",
  "physiological",
  "VO2",
  "VO2max",
  "oxygen uptake",
  "metabolic",
  "metabolism",
  "energy",
  "aerobic",
  "anaerobic",
  "lactate",
  "threshold",
  "heart rate",
  "cardiac output",
  "blood volume",
  "muscle",
  "muscular",
  "fast-twitch",
  "slow-twitch",
  "fiber type",
  "fatigue",
  "endurance",
  "strength",
  "power output",
  
  // Genetic terms
  "genetic",
  "genetics",
  "gene",
  "allele",
  "polymorphism",
  "genotype",
  "phenotype",
  "ACTN3",
  "ACE",
  "DNA",
  "hereditary",
  "heritability",
  
  // Performance terms
  "performance",
  "sprint",
  "sprinter",
  "athlete",
  "athletic",
  "elite",
  "Olympic",
  "race",
  "competition",
  "training",
  "adaptation",
  "technique",
  "skill",
  "agility",
  "balance",
  "coordination",
  "reaction time",
  "speed",
  "explosive",
  "power-to-weight",
  
  // Measurement units
  "kg",
  "cm",
  "mm",
  "m/s",
  "N",
  "W",
  "J",
  "ml/kg/min",
  "bpm",
  "Hz",
  
  // Statistical terms
  "mean",
  "average",
  "median",
  "standard deviation",
  "variance",
  "correlation",
  "regression",
  "prediction",
  "model",
  "coefficient",
  "significance",
  "p-value",
  "confidence interval"
];

export default technicalTerms;