# Site settings
title: Four Sided Triangle
description: >-
  A sophisticated multi-model optimization pipeline designed to overcome the limitations 
  of traditional RAG systems when dealing with complex domain-expert knowledge extraction.
  
baseurl: ""
url: "https://your-username.github.io/four-sided-triangle"

# Author information
author:
  name: Four Sided Triangle Team
  email: contact@example.com

# Repository information
repository: your-username/four-sided-triangle

# Theme
theme: jekyll-theme-cayman

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Highlighter
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# SEO settings
lang: en
twitter:
  username: four_sided_triangle
  card: summary_large_image

# Navigation structure based on actual components
collections:
  stages:
    output: true
    permalink: /:collection/:name/
  adr:
    output: true
    permalink: /:collection/:name/

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Architecture
    url: /architecture
    dropdown:
      - title: System Overview
        url: /architecture
      - title: Pipeline Architecture
        url: /pipeline
      - title: Core Components
        url: /core-processing
      - title: Models Overview
        url: /models
  - title: Pipeline Stages
    url: /pipeline
    dropdown:
      - title: Query Processing
        url: /stages/query-processing
      - title: Semantic ATDB
        url: /stages/semantic-atdb
      - title: Domain Knowledge
        url: /stages/domain-knowledge
      - title: Reasoning Optimization
        url: /stages/reasoning-optimization
      - title: Solution Generation
        url: /stages/solution-generation
      - title: Response Scoring
        url: /stages/response-scoring
      - title: Response Comparison
        url: /stages/response-comparison
      - title: Threshold Verification
        url: /stages/threshold-verification
  - title: API Reference
    url: /api-reference
  - title: Development
    url: /contributing
    dropdown:
      - title: Contributing
        url: /contributing
      - title: Architecture Decisions
        url: /adr/
      - title: Frontend Development
        url: /frontend-development

# Build settings
safe: true
source: .
destination: ./_site
incremental: false
keep_files:
  - .git
  - .svn

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - system.tex
  - system.pdf
  - system.log
  - system.aux
  - system.fdb_latexmk
  - system.fls
  - system.out
  - system.synctex.gz
  - README.md

# Include files in processing
include:
  - _pages

# Default settings for posts and pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "stages"
    values:
      layout: "default"
      parent: "Pipeline Stages"
  - scope:
      path: ""
      type: "adr"
    values:
      layout: "default"
      parent: "Architecture Decision Records"

# Custom variables
version: "1.0.0"
github_username: your-username
linkedin_username: four-sided-triangle 